name: Test and Publish crate

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install system dependencies
        run: sudo apt-get -y --no-install-suggests --no-install-recommends install libgeos-c1v5 libgeos-dev
      
      - name: Rust stable with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - run: cargo fmt --all -- --check
      - run: cd cosmogony && cargo test --all

      - name: Publish crate
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          [ "$TAG" = v$(cargo run -- --version | awk '{print $2}') ] \
            && cd cosmogony \
            && cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
